### ISSUE TITLE
jib-gradle-plugin: How to share image layer caches in CI

### ISSUE THREAD

**Issue by gfelbing** [GoogleContainerTools/jib#1853]
Hello,

we are happily using this plugin to build our application containers in Jenkins.

We are using the Jenkins Kubernetes Plugin to spawn a separate (empty) build pod for each built, hence it is quite difficult (and feels odd) to share a directory between the builds to use the layer caching.

Is there a another way to re-use image layer caches?

One approach I could think of would be to use the [built-in caching mechanism](https://docs.gradle.org/current/userguide/build_cache.html) of gradle.

Is there a way to use that?

**Comment by briandealwis** [comment]
Hi @gfelbing.  Are you pushing your images to a remote repository as part of your build?  We're experimenting with some work for the `jib` task to avoid downloading base image layers that already exist in the remote repository (#1673).

I don't think we had considered trying to register the base image and/or layers with Gradle's caching.

**Comment by chanseokoh** [comment]
Some questions:

- I expect you are already caching a local Maven artifact repository (such as `~/.m2`) and sharing it between pod, because otherwise it should be a huge bottleneck. How are you doing that?
- Are you talking about caching base image layers only or application layers (all other layers built by Jib) as well? If you only care about the base image layers, #1673 will make it moot, since Jib won't even download/cache base image layers after #1673.
- General question: is it technically possible to share a directory (e.g., mount a volume) between pods that Jib can read/write concurrently?

**Comment by gfelbing** [comment]
Hi, thanks for your quick reply.

@briandealwis 
Yes, we are pushing images to a remote (google container registry) using the `jib` task.

@chanseokoh 
- Currently we have all maven dependencies checked into version control and use `file()` as repository url. But we are considering using a sonatype nexus as maven proxy within the same cluster.
- I guess we are talking about caching the application layers only, as we are using `gcr.io/distroless/java:11` as base. Our aim would be to not build/push a new image to the registry when the java application didn't change (in terms of gradle states `UP-TO-DATE` or `FROM-CACHE` when executing jar/distTar)
- As we are running everything in the GCP world, we could technically purchase a Filestore Instance to get an NFS share, but I'd like to avoid that as this would be the only use case. It would be better if we could at least use a GCS bucket holding the cache.

**Comment by chanseokoh** [comment]
> Our aim would be to not build/push a new image to the registry when the java application didn't change (unchanged in terms of gradle states `UP-TO-DATE` or `FROM-CACHE` when executing jar/distTar)

Let me understand this. Currently by default, Jib caches application layers under the Gradle build directory (`<project root>/build/jib-cache`), so within a single container in a pod, if you don't do `gradle clean` and the Gradle states are `UP-TO-DATE`, Jib won't rebuild layers. Most likely it won't push those layers to a registry as well, since Jib doesn't actually push layers if they already exist in the registry.

Now, given that you asked how to share application layers between pods, I believe you are already sharing the Gradle build cache between pods, perhaps using a centralized remote Gradle build cache set up somewhere, and containers in pods connect to it. Did I understand right?

**Comment by gfelbing** [comment]
You're perfectly right.
Running the jib task twice on the same instance (or locally) without clean in between does the right thing.
Running the jib task on a cleaned state (gradle clean / fresh build pod) twice with the same git HEAD results in pushing a new image, even if the application built is fetched from cache (we use [gradle-gcs-build-cache](https://github.com/tehlers/gradle-gcs-build-cache) to share the build cache between pods.

**Comment by loosebazooka** [comment]
It shouldn't push a new image. But it probably does go through more steps to realize it's not pushing a new image. Sorry can you confirm that it is pushing a new hash? If it is, there might be something wrong in our code.

**Comment by gfelbing** [comment]
So I executed the following scenario:

- Triggering a build running the jib task only → Image pushed with hash 186598e9c1ed48abd1b7993174cdecf346009806e2a761515902ccf7d0ec2388
- Re-Triggering the build with the same parameters on the same HEAD → Image pushed with hash 90c9d6d7e9cdff2a8dfea4516c4310837d27e2a73c58e3a0e905d445f844f73d

I ran gradle with the `--profile` option.
Within the profiling, I can verify that the compile tasks weren't executed (marked as `FROM-CACHE`). 
Only the `processResources` task was not taken from cache, which is expected as the gradle doc states

> :processResources and :jar being Copy-like tasks which are not cacheable since it is generally faster to execute them.

**Comment by briandealwis** [comment]
Are you setting `useCurrentTimestamp` by any chance? Could you or your jib configuration block here?

You can configure your own NFS server within a cluster.  There's a working example in this tool: https://github.com/coollog/kash/tree/master/k8s

**Comment by gfelbing** [comment]
No, our jib config block looks like this: 
```
jib {
    from {
        image = 'gcr.io/distroless/java:11'
    }
    container {
        jvmFlags = application.applicationDefaultJvmArgs.collect { it.toString() }
    }
    to {
        image = "eu.gcr.io/[gcp-project-name]/${project.name}"
        auth {
            username = '_json_key'
            password = project.file([path/to/secret]).text
        }
    }
}
```

We even have reproducible jars:

```
jar {
    archiveFileName = "${project.name}.jar"
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
```

**Comment by briandealwis** [comment]
Hmm, I wonder what's changing between your builds.  Here's a few ways to find the differences between the images:
  - use `docker inspect` on the two images to see if there are differences in the image configurations
  - use [`container-diff`](https://github.com/GoogleContainerTools/container-diff/) to compare the image contents

**Comment by chanseokoh** [comment]
If it creates two different images from the same source, there must be something actually different in the two images. I'd dissect the two images and find out what is different. Could be something in Images configurations (creation time, some timestamp, label, env, etc.), or something different in the file system.

Back to the topic of sharing Jib's application layer cache:

First of all, note that the [application layer cache directory is configurable](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#system-properties) with `-Djib.applicationCache`, so you can set it to a directory outside of the usual Gradle build directory.

Now, from reading the Gradle build cache doc (note I have zero experience with it), I see there is a section "[Enable caching of non-cacheable tasks"](https://docs.gradle.org/current/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks). So, I wondered perhaps it might be possible to do a manual set up to cache Jib's application layer cache directory in the Gradle build cache. I think this will require carefully associating input and output (the cache directory) conditions in a correct way where `UP-TO-DATE` means Jib should not run (i.e., no need to create a new image hence no need to push), and not `UP-TO-DATE` means there's some change in inputs leading to a different image and Jib should run. But this is purely my speculation, and not sure if this is even viable or can be robust.

I think what @briandealwis said is an alternative: running an NFS server container in your cluster. The setup seems not difficult. Then you could set `-Djib.applicationCache` to use the mounted NFS. I haven't tried this though.

**Comment by briandealwis** [comment]
Just to follow-up on `container-diff`: container-diff defaults to showing size differences.  You'll probably want to diff based on the image history and file contents:
```
container-diff diff --type history --type file image1 image2
```

**Comment by gfelbing** [comment]
`container-diff diff --type history --type file` does not find any difference:
```
-----File-----

These entries have been added to eu.gcr.io/path/to/image@sha256:186598e9c1ed48abd1b7993174cdecf346009806e2a761515902ccf7d0ec2388: None

These entries have been deleted from eu.gcr.io/path/to/image@sha256:186598e9c1ed48abd1b7993174cdecf346009806e2a761515902ccf7d0ec2388: None

These entries have been changed between eu.gcr.io/path/to/image@sha256:186598e9c1ed48abd1b7993174cdecf346009806e2a761515902ccf7d0ec2388 and eu.gcr.io/path/to/image@sha256:90c9d6d7e9cdff2a8dfea4516c4310837d27e2a73c58e3a0e905d445f844f73d: None

-----History-----

Docker history lines found only in eu.gcr.io/path/to/image@sha256:186598e9c1ed48abd1b7993174cdecf346009806e2a761515902ccf7d0ec2388: None

Docker history lines found only in eu.gcr.io/path/to/image@sha256:90c9d6d7e9cdff2a8dfea4516c4310837d27e2a73c58e3a0e905d445f844f73d: None
```

The difference when comparing `docker inspect` is only showing different hashes in the fields `Id`, `RepoDigests`, `GraphDriver.Data` and `RootFS.Layers`. Latter one has only differences in the last 3 of 7 layers.

Regarding the gradle cache: We could easily configure a task to cache the `jib.applicationCache`. But unfortunately, we have a chicken-egg problem there. The jib task would only be fetched from cache if it would not have to build the image. 

Setting up a NFS would be my last line of defence, if there is no other solution.

**Comment by loosebazooka** [comment]
So in theory jib should produce the *exact* same image on all machines, so if they aren't perhaps something is wrong. Are they different architectures or operating systems?

**Comment by chanseokoh** [comment]
> `RootFS.Layers`. Latter one has only differences in the last 3 of 7 layers.

Hmm... this certainly tells that there are differences in the file systems. The digests are sha256 checksums of (uncompressed) tarballs each representing a layer (i.e., a file system for the layer). If they are different, you have something different in the files.

**Comment by chanseokoh** [comment]
> The jib task would only be fetched from cache if it would not have to build the image.

Maybe I misunderstand how this is supposed to work or the workings of the Gradle buidl cache (I'm not really a Gradle expert), but does this matter? I mean, if Jib doesn't have to build a (new, different) image, I guess there's no need to run the jib task at all (i.e., shouldn't it just skip the Jib task), no?

**Comment by gfelbing** [comment]
Well it would be necessary to run a task which output is the layerCache (which is then fetched from the buildCache) before executing jib which can use this output.

**Comment by gfelbing** [comment]
Regarding the diffs in the image file system: the contents seems to be equivalent, as container-diff shows.
Unfortunately, container-diff does not show diffs in metadata (permissions, timestamps; see https://github.com/GoogleContainerTools/container-diff/issues/308)

Is there a way to compare these metadata?

**Comment by briandealwis** [comment]
> Latter one has only differences in the last 3 of 7 layers.

Those are almost certainly your application layers.

I'm not aware of any tools that will list filesystem metadata, beyond using`docker save` and then comparing the layer tars.

**Comment by briandealwis** [comment]
Oh and what version of Jib are you using?

**Comment by gfelbing** [comment]
So I `docker save`ed the two images and compared each layer tar using `diffoscope`.
The difference in the last three layers come from the timestamps of the (toplevel) folders of 

- app
- app/classes
- app/resources
- app/libs

Their timestamps are equal to the time when the images where created. 
The folder contents' metadata (`app/classes/META-INF/`, `app/lib/*.jar`, etc.) is then equal again, everything having a timestamp of `1970-01-01 00:00:01.000000`

**Comment by gfelbing** [comment]
Regarding the version: We are currently using

`gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:1.1.0`

within our build.

**Comment by gfelbing** [comment]
Ok, so the issue seems to be fixed with #1648 in version 1.1.2.
I'll try to update the plugin and re-test.

**Comment by briandealwis** [comment]
We just released 1.4.0.  I'll close this issue since it was due to a previously fixed bug.

**Comment by gfelbing** [comment]
After the update, it works as expected.
Thanks for the great support!

**Comment by tompson** [comment]
sorry for being late to the party - 

@gfelbing does it work for you because you are using gradle-gcs-build-cache? we have the exactly same setup except we are not using gradle-gcs-build-cache and we still have the issue that all the application layers are created by jib every time

**Comment by chanseokoh** [comment]
I don't really think gradle-gcs-build-cache matters. If Jib creates different application layers every time, this is an important issue. Can you examine the layers and locate the difference? This issue thread mentions many different tools and methods to check that. `dive` is another tool to inspect an image. You can also directly look into the layer tarball files in the application cache (`<project root>/build/jib-cache` by default), assuming the difference is only from the application layers.

**Comment by chanseokoh** [comment]
@tompson I don't really think gradle-gcs-build-cache matters. If Jib creates different application layers every time, this is an important issue. Can you examine the layers and locate the difference? This issue thread mentions many different tools and methods to check that. `dive` is another tool to inspect an image. You can also directly look into the layer tarball files in the application cache (`<project root>/build/jib-cache` by default), assuming the difference is only from the application layers.

**Comment by prakashul** [comment]
Hello folks, this issue is old, hoping this is the right place
Issue: I am using Jenkins master slave running on kubernetes. I am trying to use JIB to build my java (grade) docker images. What is the best way to implement docker caching when using jib? Volume sharing does not seem feasible as the agent pods are ephemeral, and we have multiple builds running parallel (the shared volume should be ReadWriteMany?). 
It would be great if jib had a feature like Kaniko where it could use the target docker repo also as a cache repository.

Gradle: 6.3
Jib: 2.4.0
Kubernetes: 1.14

**Comment by chanseokoh** [comment]
@prakashul this is already answered in the Gitter channel, but to help others coming to the thread:

> In practice, Jib doesn't need to download base images (as long as the target repository has them, which will always be the case unless you have never pushed any image to the repoistory). Therefore, there's not much point sharing the base image cache.
>
> That leaves us only with caching application layers (<project root>/target/jib-cache in Maven or <project root>/build/jib-cache in Gradle by default), but that's per-application cache, so depending on your situation, it may not have much benefit caching them, especially when your application layers are small. Then, because it's per-application cache, unless you build the same application concurrently, maybe you can use a `ReadWriteOnce` volume if you really want to cache application layers?

**Comment by chanseokoh** [comment]
Rather, most of the time the main bottleneck in CI is Java application building itself, where Maven or Gradle repeatedly downloads a lot of artifacts into [`~/.gradle` and `~/.m2`](https://github.com/GoogleContainerTools/jib/blob/2dbfe44f9ab6f3753705f78c8640b549fb8e89fd/.travis.yml#L21-L33) for each build. To speed up building Java applications in CI, you really need to cache these directories.

**Comment by mamuf** [comment]
Hello folks. Did I understand correctly that the only way to reuse the application layers built by `jib` is to keep the jib cache (under `build/jib-cache` for Gradle) and reuse it between builds? I.e., `jib` itself is not able to detect that some of the application layers (like the first one, "other dependencies") it would build are the same ones already available in the image repository?

**Comment by chanseokoh** [comment]
- Basically, yes. If you want, you may change the location of the application layer cache by setting some property whose name I don't remember. Check the usage doc.
- If you think about it, you cannot compare layers until you have them. But Jib won't push layers that already exist in the target registry.
